### ISSUE TITLE
Control validator doesn't recognize cave or hasstructure check

### ISSUE THREAD

**Issue by wExtraBenji** [tomheaton/mcjty-website#6]
![image](https://github.com/user-attachments/assets/d6fcd263-5f7f-4623-972f-9dd8798ad3e4)
I'm trying to configure the mod such that hostile mobs in structures may spawn, but not out in the overworld, and the validator doesn't recognize "cave" or "hasstructure"
I know "cave" works because I used it in a different pack and it works fine.

**Comment by McJty** [comment]
I will fix it later. Thanks for reporting

**Comment by McJty** [comment]
Fixed
